import{a as w,i as u,S as k,l as B}from"./assets/vendor-f97a6336.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))i(n);new MutationObserver(n=>{for(const r of n)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(n){const r={};return n.integrity&&(r.integrity=n.integrity),n.referrerpolicy&&(r.referrerPolicy=n.referrerpolicy),n.crossorigin==="use-credentials"?r.credentials="include":n.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(n){if(n.ep)return;n.ep=!0;const r=s(n);fetch(n.href,r)}})();const P="32117995-da98556d394b8c9b5a96c2a58",x="https://pixabay.com/api",y=40;let p=1,h;w.defaults.baseURL=x;const A=()=>{p+=1},O=()=>{p=1},R=()=>h,L=()=>p,M=async e=>{e&&h!==e?(O(),h=e):A();const t=new URLSearchParams({q:e||h,page:p,per_page:y,image_type:"photo",orientation:"horizontal",safesearch:!0,key:P});try{const{data:s,status:i}=await w.get(`/?${t}`);if(i===429)throw u.warning({message:"Too many requests. Limit exceeded. Try again later",position:"topCenter",timeout:8e3}),new Error("Too many requests. Limit exceeded. Try again later");return{...s,newQuery:e}}catch(s){console.error(s)}},v={hidden:"visually-hidden"},E={disabled:"disabled"},m=e=>{e.classList.remove(v.hidden)},c=e=>{e.classList.add(v.hidden)},I=e=>{e.removeAttribute(E.disabled)},S=e=>{e.setAttribute(E.disabled,"")},T=e=>Array.isArray(e)&&e.length>0,$=e=>e.replace(/\s+/g," ").trim(),a={loadMoreButton:"Load More Button",infiniteScroll:"Infinite Scroll"},o={form:document.querySelector("form#search-form"),input:document.querySelector('input[name="searchQuery"]'),gallery:document.querySelector("ul.gallery"),submitBtn:document.querySelector('button[type="submit"]'),loadMoreBtn:document.querySelector("button.load-more"),toTopBtn:document.querySelector(".scroll-top-button"),loader:document.querySelector("span.loader")},z=new k(".photo-link");let d=null,f=!1;const U=()=>{const{height:e}=o.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})},N=()=>{window.scrollTo({top:0,behavior:"smooth"})},_=e=>{e.innerHTML=""},V=e=>T(e)&&e.map(t=>{const{webformatURL:s,largeImageURL:i,tags:n,likes:r,views:l,comments:g,downloads:H}=t;return`
        <li class="photo-card">
          <a class="photo-link" href="${i}">
            <img src="${s}" alt="${n}" loading="lazy" width="305" height="200" />
          </a>
          <div class="info">
              <p class="info-item">
                  <b>Likes</b>
                  ${r}
              </p>
              <p class="info-item">
                  <b>Views</b>
                  ${l}
              </p>
              <p class="info-item">
                  <b>Comments</b>
                  ${g}
              </p>
              <p class="info-item">
                  <b>Downloads</b>
                  ${H}
              </p>
          </div>
          
    </li>`}).join(""),q=e=>{const t=V(e);o.gallery.insertAdjacentHTML("beforeend",t),z.refresh()},W=B(()=>{window.scrollY>=100?m(o.toTopBtn):c(o.toTopBtn)},500),C=B(()=>{const e=document.body,t=document.documentElement;Math.max(e.scrollHeight,e.offsetHeight,t.clientHeight,t.scrollHeight,t.offsetHeight)-window.innerHeight-window.scrollY<300&&b()},500),D=e=>{const t=$(e.target.value);t&&t.length>=2?I(o.submitBtn):S(o.submitBtn)},Y=async e=>{e.preventDefault();const t=e.target.elements.searchQuery.value,s=$(t);o.form.reset(),S(o.submitBtn),d===a.loadMoreButton&&c(o.loadMoreBtn),m(o.loader),_(o.gallery);try{const i=await M(s);if(c(o.loader),!i)return;const{hits:n,totalHits:r,newQuery:l}=i;if(!T(n)){u.warning({message:`Sorry, there are no images matching "${l}". Please try another search`,position:"topCenter",timeout:4e3});return}if(u.success({message:`Hooray! We found ${r} images.`,position:"topCenter",timeout:1500}),q(n),window.addEventListener("scroll",W),d===a.loadMoreButton){const g=L();f=r<g*y,f?c(o.loadMoreBtn):(m(o.loadMoreBtn),o.loadMoreBtn.addEventListener("click",b))}else window.addEventListener("scroll",C)}catch(i){console.log(i)}},b=async()=>{d===a.loadMoreButton&&c(o.loadMoreBtn),m(o.loader);try{const e=R(),t=await M(e);if(c(o.loader),!t)return;const{hits:s,totalHits:i}=t;q(s),U();const n=L();if(f=i<n*y,f){window.removeEventListener("scroll",C),o.loadMoreBtn.removeEventListener("click",b),setTimeout(()=>{u.warning({message:"We're sorry, but you've reached the end of search results.",position:"topCenter",timeout:3500})},1e3),d===a.loadMoreButton&&c(o.loadMoreBtn);return}d===a.loadMoreButton&&m(o.loadMoreBtn)}catch(e){console.log(e)}},j=()=>{u.question({timeout:2e4,close:!1,overlay:!0,displayMode:"once",id:"question",zindex:999,message:"Which modes do you want to use?",position:"center",buttons:[[`<button>${a.loadMoreButton}</button>`,function(e,t){e.hide({transitionOut:"fadeOut"},t,`${a.loadMoreButton}`)}],[`<button>${a.infiniteScroll}</button>`,function(e,t){e.hide({transitionOut:"fadeOut"},t,`${a.infiniteScroll}`)}]],onClosed:function(e,t,s){d=s==="timeout"?`${a.loadMoreButton}`:`${s}`}})};j();o.input.addEventListener("input",D);o.form.addEventListener("submit",Y);o.toTopBtn.addEventListener("click",N);
//# sourceMappingURL=commonHelpers.js.map
