import{a as w,i as c,S as P,l as v}from"./assets/vendor-f97a6336.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))i(n);new MutationObserver(n=>{for(const r of n)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(n){const r={};return n.integrity&&(r.integrity=n.integrity),n.referrerpolicy&&(r.referrerPolicy=n.referrerpolicy),n.crossorigin==="use-credentials"?r.credentials="include":n.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(n){if(n.ep)return;n.ep=!0;const r=s(n);fetch(n.href,r)}})();const x="32117995-da98556d394b8c9b5a96c2a58",A="https://pixabay.com/api",B=40;let p=1,h;w.defaults.baseURL=A;const O=()=>{p+=1},R=()=>{p=1},L=()=>h,I=()=>p,M=async e=>{e&&h!==e?(R(),h=e):O();const t=new URLSearchParams({q:e||h,page:p,per_page:B,image_type:"photo",orientation:"horizontal",safesearch:!0,key:x});try{return await w.get(`/?${t}`)}catch(s){console.error(s)}},E={hidden:"visually-hidden"},S={disabled:"disabled"},m=e=>{e.classList.remove(E.hidden)},d=e=>{e.classList.add(E.hidden)},z=e=>{e.removeAttribute(S.disabled)},T=e=>{e.setAttribute(S.disabled,"")},C=e=>Array.isArray(e)&&e.length>0,$=e=>e.replace(/\s+/g," ").trim(),k=e=>{if(e===429)throw c.warning({message:"Too many requests. Limit exceeded. Try again later",position:"topCenter",timeout:8e3}),new Error("Too many requests. Limit exceeded. Try again later")},U=()=>{window.scrollTo({top:0,behavior:"smooth"})},y=e=>{const t=I();return e<t*B},a={loadMoreButton:"Load More Button",infiniteScroll:"Infinite Scroll"},o={form:document.querySelector("form#search-form"),input:document.querySelector('input[name="searchQuery"]'),gallery:document.querySelector("ul.gallery"),submitBtn:document.querySelector('button[type="submit"]'),loadMoreBtn:document.querySelector("button.load-more"),toTopBtn:document.querySelector(".scroll-top-button"),loader:document.querySelector("span.loader")},N=new P(".photo-link");let u=null;const Y=()=>{const{height:e}=o.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})},_=e=>{e.innerHTML=""},V=e=>C(e)&&e.map(t=>{const{webformatURL:s,largeImageURL:i,tags:n,likes:r,views:l,comments:g,downloads:H}=t;return`
        <li class="photo-card">
          <a class="photo-link" href="${i}">
            <img src="${s}" alt="${n}" loading="lazy" width="305" height="200" />
          </a>
          <div class="info">
              <p class="info-item">
                  <b>Likes</b>
                  ${r}
              </p>
              <p class="info-item">
                  <b>Views</b>
                  ${l}
              </p>
              <p class="info-item">
                  <b>Comments</b>
                  ${g}
              </p>
              <p class="info-item">
                  <b>Downloads</b>
                  ${H}
              </p>
          </div>
          
    </li>`}).join(""),q=e=>{const t=V(e);o.gallery.insertAdjacentHTML("beforeend",t),N.refresh()},W=v(()=>{window.scrollY>=100?m(o.toTopBtn):d(o.toTopBtn)},500),b=v(()=>{const e=document.body,t=document.documentElement;Math.max(e.scrollHeight,e.offsetHeight,t.clientHeight,t.scrollHeight,t.offsetHeight)-window.innerHeight-window.scrollY<300&&f()},500),D=e=>{const t=$(e.target.value);t&&t.length>=2?z(o.submitBtn):T(o.submitBtn)},j=async e=>{e.preventDefault();const t=e.target.elements.searchQuery.value,s=$(t);o.form.reset(),T(o.submitBtn),u===a.loadMoreButton&&d(o.loadMoreBtn),m(o.loader),_(o.gallery);try{const{data:i,status:n}=await M(s);if(d(o.loader),k(n),!i)return;const{hits:r,totalHits:l}=i,g=L();if(!C(r)){c.warning({message:`Sorry, there are no images matching "${g}". Please try another search`,position:"topCenter",timeout:4e3});return}if(c.success({message:`Hooray! We found ${l} images.`,position:"topCenter",timeout:1500}),q(r),window.addEventListener("scroll",W),u===a.infiniteScroll){y(l)?(window.removeEventListener("scroll",b),c.warning({message:"You've reached the end of search results.",position:"topCenter",timeout:2500})):window.addEventListener("scroll",b);return}u===a.loadMoreButton&&(y(l)?(d(o.loadMoreBtn),o.loadMoreBtn.removeEventListener("click",f),c.warning({message:"You've reached the end of search results.",position:"topCenter",timeout:2500})):(m(o.loadMoreBtn),o.loadMoreBtn.addEventListener("click",f)))}catch(i){console.log(i)}},f=async()=>{u===a.loadMoreButton&&d(o.loadMoreBtn),m(o.loader);try{const e=L(),{data:t,status:s}=await M(e);if(d(o.loader),k(s),!t)return;const{hits:i,totalHits:n}=t;if(q(i),Y(),y(n)){window.removeEventListener("scroll",b),o.loadMoreBtn.removeEventListener("click",f),setTimeout(()=>{c.warning({message:"We're sorry, but you've reached the end of search results.",position:"topCenter",timeout:3500})},1e3),u===a.loadMoreButton&&d(o.loadMoreBtn);return}u===a.loadMoreButton&&m(o.loadMoreBtn)}catch(e){console.log(e)}},F=()=>{c.question({timeout:2e4,close:!1,overlay:!0,displayMode:"once",id:"question",zindex:999,message:"Which modes do you want to use?",position:"center",buttons:[[`<button>${a.loadMoreButton}</button>`,function(e,t){e.hide({transitionOut:"fadeOut"},t,`${a.loadMoreButton}`)}],[`<button>${a.infiniteScroll}</button>`,function(e,t){e.hide({transitionOut:"fadeOut"},t,`${a.infiniteScroll}`)}]],onClosed:function(e,t,s){u=s==="timeout"?`${a.loadMoreButton}`:`${s}`}})};F();o.input.addEventListener("input",D);o.form.addEventListener("submit",j);o.toTopBtn.addEventListener("click",U);
//# sourceMappingURL=commonHelpers.js.map
